### ISSUE TITLE
Node example throws error 

### ISSUE THREAD

**Issue by nilslice** [TheLunarCompany/lunar#17]
Using `"lunar-interceptor": "^2.1.3"`

```
Press Enter to get Cat Facts...

Sending a request to https://catfact.ninja/fact every 2 seconds
Press Enter to stop...

node:internal/url:775
    this.#updateContext(bindingUrl.parse(input, base));
                                   ^

TypeError: Invalid URL
    at new URL (node:internal/url:775:36)
    at generateUrl (/Users/steve/Projects/dylibso/xtp-lunar/node_modules/lunar-interceptor/dist/helper.js:54:12)
    at LunarInterceptor.generateModifiedOptions (/Users/steve/Projects/dylibso/xtp-lunar/node_modules/lunar-interceptor/dist/interceptor.js:257:54)
    at LunarInterceptor.httpHookRequestFunc (/Users/steve/Projects/dylibso/xtp-lunar/node_modules/lunar-interceptor/dist/interceptor.js:212:40)
    at LunarInterceptor.httpHookGetFunc (/Users/steve/Projects/dylibso/xtp-lunar/node_modules/lunar-interceptor/dist/interceptor.js:177:21)
    at Timeout.getCatFact [as _onTimeout] (/Users/steve/Projects/dylibso/xtp-lunar/index.js:15:11)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_INVALID_URL',
  input: 'http://localhost:8000undefined'
}

Node.js v20.11.1
```

**Comment by eitangol** [comment]
Hey @nilslice, thanks for reporting this issue.
We fix the problem and you can try again using version 2.1.4 of our [NodeJS Interceptor](https://www.npmjs.com/package/lunar-interceptor/v/2.1.4)

**Comment by eitangol** [comment]
Hey @nilslice, thanks for reporting this issue.
We fix the problem and you can try again using version 2.1.4 of our [NodeJS Interceptor](https://www.npmjs.com/package/lunar-interceptor/v/2.1.4)
